---
# tasks file for osp-facts
- name: create bin directory
  file:
    path: /root/bin
    state: directory

- name: copy script to get aws_collect_dependencies
  copy:
    src: aws_collect_dependencies.sh
    dest: /root/aws_collect_dependencies.sh
    mode: 755

- name: Execute the aws_collect_dependencies shell script and collect logs
  command: sh /root/aws_collect_dependencies.sh 

- name: copy credential rc
  copy:
    src: credential.rc
    dest: /root/credential.rc
    mode: 755

# Using this script will always deploy environments in the us-east-1 region.

- name: copy provision-infra.sh
  copy:
    src: aws_provision_infra.sh
    dest: /root/aws_provision_infra.sh
    mode: 755

- name: Execute the provision command
  command: sh /root/aws_provision_infra.sh

# - name: run final command to order instances
#   command: source credential.rc; order_svc.sh -y -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1

- name: Wait for environments to provision
  pause:
    minutes: 5